DFdb Documentation: DFdb.db.DFdatabase Class Reference
DFdb.db.DFdatabase Class Reference
Class which handles all database communication.
Public Member Functions
def __init__ (self, db_file, mode, options=None)
Initialise DFdatabase object.
def add_relaxed (self, struct_file, eqm_struct=None)
Load a single relaxed structure into the database.
def add_batch (self, traj_file, relaxed, eqm_struct=None)
Loads all structures in a single .traj file into the database.
def add_unrelaxed (self, struct_file)
Load a single unrelaxed structure into the database.
def add_reaction (self, reac_file, nimages)
Load the end state of a NEB calculation into the database.
def get_row_info (self, row)
Display pertinent information about a selected ASE.db row.
def get (self, selection=None, **kwargs)
Select a single row and return it as a dictionary.
def select (self, selection=None, filter=None, explain=False, verbosity=1, limit=None, offset=0, sort=None, include_data=True, columns='all', **kwargs)
Select rows, return as a list.
def export (self, row, filetype='xyz', filename=None)
Exports the Atoms object within the given row to a file.
def __struct_parser__ (self, struct_file, relaxed)
Inbuilt method for parsing structure names into key/value pairs for entry into the database.
def __calc_parser__ (self, atoms)
Inbuilt method for parsing calculator details from a finished calculation.
def __reac_parser__ (self, reaction, reac_file)
Inbuilt method for parsing reaction details from a finished NEB calculation.
Public Attributes
db_file
mode
dc
options
modification_list
Detailed Description
Class which handles all database communication.
Contains functions to ingest new structures and reaction paths, identify those in need of optimisation, and to submit optimisations on these jobs.
Parameters
db_file Path to the ASE database file. options (optional) DFoptions instance.
Definition at line 20 of file db.py.
Constructor & Destructor Documentation
__init__()
def DFdb.db.DFdatabase.__init__ (self, db_file, mode, options = None)
Initialise DFdatabase object.
   Load in ASE database if it exists, else create a new one and load
   that in.
   If a DFoptions instance is provided, attach it here. Otherwise,
   initialise DFdatabase with default options.
Definition at line 30 of file db.py.
         '''
         self.db_file = db_file
         self.mode = mode
         if self.mode not in ('geometry', 'reaction'):
             raise ValueError('Unknown database mode, must be either `geometry` or `reaction`.')
         if not os.path.isfile(self.db_file):
             print(f'Database file {self.db_file} not found, creating a new one.')
             self.dc = ase.db.connect(self.db_file)
             self.dc.metadata = {
                 'title': 'DFdb Comparative Database',
                 'db_mode': self.mode
                 }
             if self.mode == 'reaction':
                 _metadata = self.dc.metadata
                 _metadata.update({'num_reacs': 0})
                 self.dc.metadata = _metadata
             # Hacky workaround fix for the database needing to be refreshed before displaying metadata.
             self.dc = ase.db.connect(self.db_file)
         else:
             self.dc = ase.db.connect(self.db_file)
             if self.dc.metadata['db_mode'] != self.mode:
                 raise ValueError('Given database mode does not match the type of the existing database.')
         if options:
             self.options = options
         else:
             self.options = DFoptions()
         self.modification_list = [
             '_MS',
             '_ES',
             '_PrS',
             '_PhS',
             'Hyd_',
             'Cross_',
             '_MC',
             '_EC',
             '_PrC',
             '_PhC'
         ]
     def add_relaxed(self, struct_file, eqm_struct=None):
         '''Load a single relaxed structure into the database.
Member Function Documentation
add_relaxed()
def DFdb.db.DFdatabase.add_relaxed (self, struct_file, eqm_struct = None)
Load a single relaxed structure into the database.
   Structures added into the database this way get tagged as
   `relaxed`, as well as being tagged with their relevant calculator.
Parameters
struct_file Path (not including path to relaxed_folder in DFoptions) to relaxed structure. eqm_struct Boolean signifying if this structure is GS or non-equilibrium, eg. from minima hopping.
Definition at line 85 of file db.py.
         struct_dict, extra_data = self.__struct_parser__(struct_file, relaxed=True)
         calc_dict, calc_data = self.__calc_parser__(struct)
         struct_dict.update(calc_dict)
         if eqm_struct is not None and type(eqm_struct) == bool:
             struct_dict.update({'equilibrium_structure': eqm_struct})
         extra_data.update(calc_data)
         self.dc.write(
             struct,
             key_value_pairs=struct_dict,
             data=extra_data
             )
     def add_batch(self, traj_file, relaxed, eqm_struct=None):
         '''Loads all structures in a single .traj file into the database.
References DFdb.db.DFdatabase.__calc_parser__(), DFdb.db.DFdatabase.__struct_parser__(), and DFdb.db.DFdatabase.dc.
add_batch()
def DFdb.db.DFdatabase.add_batch (self, traj_file, relaxed, eqm_struct = None)
Loads all structures in a single .traj file into the database.
   Useful for adding all structures from a minima hopping run into
   the database, in which case "relaxed=False" should be interpreted
   as structures with their original inaccurate energies and forces,
   while "relaxed=True" means that the energies/forces have been updated
   to the level of accuracy needed from the respective method.
   In the case that the structures are from minima hopping, equ_struct
   should be set to False so these structures are identifiable.
   The .traj file should start with "batch_", followed by the name of the
   structures contained within it.
Parameters
traj_file Path to traj file containing relaxed structures. relaxed Boolean signifying whether the structures are in their final state or require further calculation. eqm_struct Boolean signifying if this structure is GS or non-equilibrium, eg. from minima hopping.
Definition at line 122 of file db.py.
         if  name[:6] != 'batch_':
             raise ValueError('traj_file is not a batch job trajectory.')
         traj = read(f'{traj_file}', index=':')
         for struct in traj:
             struct_dict, extra_data = self.__struct_parser__(name_ext[6:], relaxed=relaxed)
             calc_dict, calc_data = self.__calc_parser__(struct)
             struct_dict.update(calc_dict)
             if eqm_struct is not None and type(eqm_struct) == bool:
                 struct_dict.update({'equilibrium_structure': eqm_struct})
                 extra_data.update(calc_data)
             self.dc.write(
                 struct,
                 key_value_pairs=struct_dict,
                 data=extra_data
             )
     def add_unrelaxed(self, struct_file):
         '''Load a single unrelaxed structure into the database.
References DFdb.db.DFdatabase.__calc_parser__(), DFdb.db.DFdatabase.__struct_parser__(), and DFdb.db.DFdatabase.dc.
add_unrelaxed()
def DFdb.db.DFdatabase.add_unrelaxed (self, struct_file)
Load a single unrelaxed structure into the database.
   This structure will be tagged as unrelaxed and will not have an
   associated calculator tag.
Parameters
struct_file Path (not including path to unrelaxed_folder in DFoptions) to relaxed structure.
Definition at line 153 of file db.py.
         struct_dict, extra_data = self.__struct_parser__(struct_file, relaxed=False)
         self.dc.write(
             struct,
             key_value_pairs=struct_dict,
             data=extra_data
             )
     def add_reaction(self, reac_file, nimages):
         '''Load the end state of a NEB calculation into the database.
References DFdb.db.DFdatabase.__struct_parser__(), and DFdb.db.DFdatabase.dc.
add_reaction()
def DFdb.db.DFdatabase.add_reaction (self, reac_file, nimages)
Load the end state of a NEB calculation into the database.
   The final [nimages] of the provided trajectory will be loaded into
   the database and tagged under their reaction name, as well as a
   unique reaction id and their respective calculator.
   The transition state will be assumed to be the highest energy of
   the images, and will be marked as such with the `TS` tag.
Parameters
reac_file Path (not including path to reaction_folder in DFoptions) to NEB trajectory.
Definition at line 178 of file db.py.
         reac_dict_list, extra_data_list = self.__reac_parser__(reaction, reac_file)
         for i, image in enumerate(reaction):
             self.dc.write(
                 image,
                 key_value_pairs=reac_dict_list[i],
                 data=extra_data_list[i]
                 )
     def get_row_info(self, row):
         '''Display pertinent information about a selected ASE.db row.
References DFdb.db.DFdatabase.__reac_parser__(), and DFdb.db.DFdatabase.dc.
get_row_info()
def DFdb.db.DFdatabase.get_row_info (self, row)
Display pertinent information about a selected ASE.db row.
Parameters
row An ASE AtomsRow object, obtained using DFdatabase.dc.get() or .select().
Definition at line 197 of file db.py.
             f'---------------------\n'
             f'  Structure name: {row.struct_name}\n'
             f'  Formula: {row.formula}\n'
             f'  Polymeric: {"Yes" if row.polymeric else "No"}'
         ))
         if row.relaxed:
             print((
                 f'  Relaxed: Yes\n'
                 f'  Calculator: {row.calculator}'
             ))
             if row.DFTcalc:
                 print(f'  DFT Functional: {row.DFTfunctional}')
             if row.DFTBcalc:
                 print(f'  DFTB+ Parameter Set: {row.DFTBparamset}')
         else:
             print('  Relaxed: No')
         print('')
         print(f'  Energy: {row.energy} eV')
     def get(self, selection=None, **kwargs):
         '''Select a single row and return it as a dictionary.
get()
def DFdb.db.DFdatabase.get (self, selection = None, ** kwargs)
Select a single row and return it as a dictionary.
   Shortcut to Dfdatabase.dc.get(). Refer to ase/db/core.py for full
   documentation.
Parameters
selection int, str or list See the select() method.
Definition at line 230 of file db.py.
     def select(self, selection=None, filter=None, explain=False,
                verbosity=1, limit=None, offset=0, sort=None,
                include_data=True, columns='all', **kwargs):
References DFdb.db.DFdatabase.dc.
select()
def DFdb.db.DFdatabase.select (self, selection = None, filter = None, explain = False, verbosity = 1, limit = None, offset = 0, sort = None, include_data = True, columns = 'all', ** kwargs)
Select rows, return as a list.
   Wrapper for Dfdatabase.dc.select() which returns a list instead
   of a lazy iterator. Refer to ase/db/core.py for full documentation.
   Return list with results.  Selection is done using key-value pairs
   and the special keys:
formula age user calculator natoms energy magmom and/or charge.
Parameters
selection int, str or list Can be:
an integer id
a string like 'key=value', where '=' can also be one of '<=', '<', '>', '>=' or '!='.
a string like 'key'
comma separated strings like 'key1<value1,key2=value2,key'
list of strings or tuples: [('charge', '=', 1)]. filter function A function that takes as input a row and returns True or False. explain bool Explain query plan. verbosity int Possible 0, 1 or 2. limit int or None Limit selection. offset int Offset into selected rows. sort str Sort rows after key. Prepend with minus sign for a decending sort. include_data bool Use include_data=False to skip reading data from rows. columns 'all' or list of str Specify which columns from the SQL table to include. For example, if only the row id and the energy is needed, queries can be speeded up by setting columns=['id', 'energy'].
Definition at line 280 of file db.py.
         The resulting file will be placed in the [export_path] of the current DFoptions
         instance, with a name corresponding to the struct_name of the row and the given
         filetype (unless filename is given, which overrides this).
         Parameters:
References DFdb.db.DFdatabase.dc.
export()
def DFdb.db.DFdatabase.export (self, row, filetype = 'xyz', filename = None)
Exports the Atoms object within the given row to a file.
   The resulting file will be placed in the [export_path] of the current DFoptions
   instance, with a name corresponding to the struct_name of the row and the given
   filetype (unless filename is given, which overrides this).
Parameters
row Either a single AtomsRow object or a list of AtomsRows, obtained via DFdatabase.select() or DFdatabase.get(). filetype (Default: xyz, Choices: [xyz, traj]) The type of file to export as. filename (Optional) Override for default filename.
Definition at line 301 of file db.py.
                 raise ValueError('filename must be a string!')
             file_out = filename
         else:
             file_out = f'{row.struct_name}.{filetype}'
         write(f'{self.options.o["export_folder"]}/{file_out}', atoms, format=filetype)
         print(f'Structure written to {self.options.o["export_folder"]}/{file_out}')
     def __struct_parser__(self, struct_file, relaxed):
         '''Inbuilt method for parsing structure names into key/value pairs
         for entry into the database.
         '''
         subfolder, name_ext = os.path.split(struct_file)
         name, ext = os.path.splitext(name_ext)
         if 'OHC' in name:
             end_group = 'OHC'
__struct_parser__()
def DFdb.db.DFdatabase.__struct_parser__ (self, struct_file, relaxed)
Inbuilt method for parsing structure names into key/value pairs for entry into the database.
Definition at line 322 of file db.py.
             end_group = 'N/A'
         polymeric = True if end_group != 'N/A' else False
         if any(substring in name for substring in self.modification_list):
             pure_struct = False
         else:
             pure_struct = True
         if 'Cross_' in name:
             frag_type = 'crosslinking'
         elif 'Hyd_' in name:
             frag_type = 'hydration'
         else:
             frag_type = ''
         struct_dict = {
             'relaxed': relaxed,
             'struct_name': name,
             'end_group': end_group,
             'pure_struct': pure_struct,
             'polymeric': polymeric
         }
         extra_data = {
             'frag_type': frag_type
         }
         return struct_dict, extra_data
     def __calc_parser__(self, atoms):
         '''Inbuilt method for parsing calculator details from a finished
         calculation.
         In the event that a DFT calculation was done, report back the functional.
         In the event that a DFTB calculation was done, report back the parameter
         set.
         '''
         calc = atoms.get_calculator()
References DFdb.db.DFdatabase.modification_list.
Referenced by DFdb.db.DFdatabase.add_batch(), DFdb.db.DFdatabase.add_relaxed(), and DFdb.db.DFdatabase.add_unrelaxed().
__calc_parser__()
def DFdb.db.DFdatabase.__calc_parser__ (self, atoms)
Inbuilt method for parsing calculator details from a finished calculation.
In the event that a DFT calculation was done, report back the functional. In the event that a DFTB calculation was done, report back the parameter set.
Definition at line 368 of file db.py.
         return calc_dict, extra_data
     def __reac_parser__(self, reaction, reac_file):
         '''Inbuilt method for parsing reaction details from a finished NEB calculation.
         Assumes the highest energy image in `reaction` is the transition state,
         and tags it as such. Returns a list of dictionaries, one for each image.
         '''
         energies = np.zeros(len(reaction))
         for i, image in enumerate(reaction):
             energies[i] = image.get_potential_energy()
Referenced by DFdb.db.DFdatabase.__reac_parser__(), DFdb.db.DFdatabase.add_batch(), and DFdb.db.DFdatabase.add_relaxed().
__reac_parser__()
def DFdb.db.DFdatabase.__reac_parser__ (self, reaction, reac_file)
Inbuilt method for parsing reaction details from a finished NEB calculation.
   Assumes the highest energy image in `reaction` is the transition state,
   and tags it as such. Returns a list of dictionaries, one for each image.
Definition at line 386 of file db.py.
         if 'Cross_' in reac_name:
             reac_type = 'crosslinking'
         elif 'Hyd_' in reac_name:
             reac_type = 'hydration'
         else:
             reac_type = ''
         dict_list = []
         data_list = []
         for i, image in enumerate(reaction):
             reac_dict = {
                 'reac_name': reac_name,
                 'reac_id': reac_id,
                 'reac_TS': True if i==ts_index else False,
                 'reac_start': True if i==0 else False,
                 'reac_end': True if i==len(reaction) else False,
                 'reac_type': reac_type
             }
             calc_dict, calc_data = self.__calc_parser__(image)
             reac_dict.update(calc_dict)
             dict_list.append(calc_dict)
             data_list.append(calc_data)
         return dict_list, data_list
References DFdb.db.DFdatabase.__calc_parser__(), and DFdb.db.DFdatabase.dc.
Referenced by DFdb.db.DFdatabase.add_reaction().
Member Data Documentation
db_file
DFdb.db.DFdatabase.db_file
Definition at line 31 of file db.py.
mode
DFdb.db.DFdatabase.mode
Definition at line 32 of file db.py.
dc
DFdb.db.DFdatabase.dc
Definition at line 37 of file db.py.
Referenced by DFdb.db.DFdatabase.__reac_parser__(), DFdb.db.DFdatabase.add_batch(), DFdb.db.DFdatabase.add_reaction(), DFdb.db.DFdatabase.add_relaxed(), DFdb.db.DFdatabase.add_unrelaxed(), DFdb.db.DFdatabase.get(), and DFdb.db.DFdatabase.select().
options
DFdb.db.DFdatabase.options
Definition at line 57 of file db.py.
Referenced by DFdb.submit.SLURMsubmit.batch_get_energies(), and DFdb.submit.SLURMsubmit.relax().
modification_list
DFdb.db.DFdatabase.modification_list
Definition at line 61 of file db.py.
Referenced by DFdb.db.DFdatabase.__struct_parser__().
The documentation for this class was generated from the following file:
repo/DFdb/db.py