DFdb Documentation: DFdb.analyse.DFanalysis Class Reference
DFdb.analyse.DFanalysis Class Reference
Handles analysis and plotting of comparative results.
Public Member Functions
def __init__ (self, skl_kde_samples=10000)
Initialise DFanalysis object.
def plot_position_difference (self, reference, comparisons, ignore_H=False, plot_type='hist', reference_name=None, comparison_names=None, title=None, return_data=False, savefig=None)
Plot the lRMSDs of atomic positions between the molecules in DFdb sets compared to a reference set.
def plot_force_difference (self, reference, comparisons, plot_type='hist', reference_name=None, comparison_names=None, title=None, return_data=False, savefig=None)
Plot the RMSDs of atomic forces between the molecules in DFdb sets compared to a reference set.
def plot_energy_difference (self, reference_set, comparison_sets, plot_type='hist', reference_name=None, comparison_names=None, title=None, return_data=False, savefig=None)
Plot the energy differences between identically structured molecules in DFdb sets compared to a reference set.
Public Attributes
skl_kde_samples
int
Private Member Functions
def _compare_positions (self, arl1, arl2, ignore_H=False)
Calculate the (least)RMSDs of atomic positions between the molecules in two DFdb sets.
def _compare_forces (self, arl1, arl2)
Calculate the RMSDs of atomic forces between the molecules in two DFdb sets.
def _compare_energies (self, arl1, arl2)
Compare relative energies of the molecules in two DFdb sets.
Detailed Description
Handles analysis and plotting of comparative results.
Contains functions to extract a range of comparative properties from lists of AtomsRows, as well as plotting functions to combine their outputs into publication-quality graphs.
        Number of samples to evaluate Scikit-learn KDE plots over
        when calculating sample means and vaiances.
Definition at line 34 of file analyse.py.
Constructor & Destructor Documentation
__init__()
def DFdb.analyse.DFanalysis.__init__ (self, skl_kde_samples = 10000)
Initialise DFanalysis object.
Definition at line 40 of file analyse.py.
     def plot_position_difference(self, reference, comparisons, ignore_H=False, plot_type='hist',
                                  reference_name=None, comparison_names=None, title=None,
                                  return_data=False, savefig=None):
         '''Plot the lRMSDs of atomic positions between the molecules in DFdb sets compared to a reference set.
Member Function Documentation
plot_position_difference()
def DFdb.analyse.DFanalysis.plot_position_difference (self, reference, comparisons, ignore_H = False, plot_type = 'hist', reference_name = None, comparison_names = None, title = None, return_data = False, savefig = None)
Plot the lRMSDs of atomic positions between the molecules in DFdb sets compared to a reference set.
   Either uses Seaborn to produce a rough histogram or histogram+KDE plot, or
   uses Scikit-learn to fit an accurate KDE plot and report mean and variance
   of the resulting data.
   Return 0 is a Pandas DataFrame containing the accurate results from the KDE fit
   if the Scikit-learn implementation is used, else return 0 is None. Return 1 is
   a Pandas DataFrame of all the position lRMSDs if return_data is true, else return 1 is
   None.
Parameters
reference list List of AtomsRows with identical chemical formulae to those in comparison.
comparisons list List of comparative lists of AtomsRows with identical chemical formulae to those in reference.
ignore_H boolean; Default: False Whether to ignore hydrogens in the RMSD calculation.
plot_type str; Default: hist; Choices: [hist, hist+kde, kde] The type of plot to produce.
reference_name str; Optional Name of the reference dataset.
comparison_names list of strings; Optional List of names of the comparison datasets.
title str; Optional Figure title for the graph.
return_data boolean; Default: False Whether to include a DataFrame of all the lRMSD data used in plotting.
savefig str or None; Optional Whether to save the figure to file. Leaving as None means no saving, otherwise a string containing the path to save to should be passed.
Returns
If the Scikit-learn implementation is used, the first return value is a Pandas DataFrame containing the accurate results from the KDE fit. Otherwise, this value returns None. If return_data is True then the second return value is a Pandas DataFrame of all the position lRMSDs, otherwise this value returns None.
Definition at line 85 of file analyse.py.
             'hist+kde',
             'kde'
         ]
         if plot_type not in plot_types:
             raise ValueError('Unrecognised plot_type! Must be one of [hist, hist+kde, kde].')
             raise Err
         # Check there are the correct number of comparison_names for the number of datasets, if names are provided.
         num_plots = len(comparisons)
         if comparison_names:
             if not len(comparison_names)==num_plots:
                 raise ValueError('Number of strings in comparison_names doesn\'t match number of comparative lists.')
         # Check that savefig is valid, if present.
         if savefig:
             if type(savefig) is not str:
                 raise ValueError('Argument savefig should be None or a string.')
         # Calculate lRMSDs for each comparative dataset.
         rmsds = [self._compare_positions(reference, comparison, ignore_H) for comparison in comparisons]
         # Gather struct_name data if needed.
         if return_data:
             mol_names = [row.struct_name for row in reference]
         output = [None, None]
         # Plot results.
         if plot_type == 'kde':
             # Generate an accurate KDE plot with Scikit-learn and report mean/variance.
             fig, ax = plt.subplots(1, num_plots, sharey=True, constrained_layout=True, figsize=(10*num_plots, 10))
             sample_means = np.zeros(num_plots)
             means = np.zeros(num_plots)
             sample_variances = np.zeros(num_plots)
             variances = np.zeros(num_plots)
             sample_stdevs = np.zeros(num_plots)
             stdevs = np.zeros(num_plots)
             for i, rmsd_list in enumerate(rmsds):
                 x = np.linspace(min(rmsd_list), max(rmsd_list), 1000)
                 bandwidths = 10**np.linspace(-1, 1, 100)
                 grid = GridSearchCV(KernelDensity(kernel='gaussian'), {'bandwidth': bandwidths}, cv=LeaveOneOut().split(rmsd_list))
                 grid.fit(rmsd_list[:, None])
                 kde = KernelDensity(bandwidth=grid.best_params_['bandwidth'], kernel='gaussian')
                 kde.fit(rmsd_list[:, None])
                 logprob = kde.score_samples(x[:, None])
                 means[i] = np.mean(rmsd_list)
                 variances[i] = np.var(rmsd_list)
                 stdevs[i] = np.sqrt(variances[i])
                 sample_means[i] = np.mean(kde.sample(self.skl_kde_samples))
                 sample_variances[i] = np.var(kde.sample(self.skl_kde_samples))
                 sample_stdevs[i] = np.sqrt(sample_variances[i])
                 ax[i].fill_between(x, np.exp(logprob), alpha=0.5)
                 if i == 0:
                     ax[i].set_ylabel('Probability')
                 ax[i].set_xlabel(r'lRMSD of atomic positions ($\AA$/atom)')
                 if reference_name and comparison_names:
                     ax[i].set_title(f'{reference_name} vs {comparison_names[i]}')
             # Assemble DataFrame of statistical information for the KDE plot.
             stats_df = pd.DataFrame({
                 'Comparison': [f'{reference_name} vs {comparison_names[i]}' for i in range(num_plots)],
                 'Raw Data Mean': means,
                 'Sample Mean': sample_means,
                 'Raw Data Variance': variances,
                 'Sample Variance': sample_variances,
                 'Raw Data Stdev': stdevs,
                 'Sample Stdev': sample_stdevs
             })
             output[0] = stats_df
         else:
             # Generate a rough histogram/KDE plot with seaborn.
             fig, ax = plt.subplots(1, num_plots, sharey=True, constrained_layout=True, figsize=(10*num_plots, 10))
             for i, rmsd_list in enumerate(rmsds):
                 sns.histplot(rmsd_list, bins=15, kde=(True if plot_type=='hist+kde' else False), ax=ax[i])
                 ax[i].set_xlabel(r'lRMSD of atomic positions ($\AA$/atom)')
                 if reference_name and comparison_names:
                     ax[i].set_title(f'{reference_name} vs {comparison_names[i]}')
         if title:
             fig.suptitle(title)
         if savefig:
             fig.savefig(savefig, dpi=300)
         plt.show()
         # Assemble the full labelled lRMSD DataFrame is requested.
         if return_data:
             data1 = pd.DataFrame(mol_names, columns=['struct_name'])
             data2 = pd.DataFrame(np.array(rmsds).T, columns=[f'{reference_name} vs {comparison_names[i]}' for i in range(num_plots)])
             data3 = pd.concat([data1, data2], axis=1)
             output[1] = data3
         return output[0], output[1]
     def _compare_positions(self, arl1, arl2, ignore_H=False):
         '''Calculate the (least)RMSDs of atomic positions between the molecules in two DFdb sets.
         The molecules in each of the sets should be calculated from the
References DFdb.analyse.DFanalysis._compare_positions(), and DFdb.analyse.DFanalysis.skl_kde_samples.
_compare_positions()
def DFdb.analyse.DFanalysis._compare_positions (self, arl1, arl2, ignore_H = False) private
Calculate the (least)RMSDs of atomic positions between the molecules in two DFdb sets.
   The molecules in each of the sets should be calculated from the
   same structure files to ensure identical atomic mapping.
Parameters
arl1 list List of AtomsRows containing a set of AtomsRows with identical chemical formulae to those in ari2.
arl2 list List of AtomsRows containing a set of AtomsRows with identical chemical formulae to those in ari1.
ignore_H boolean; Default: False Whether to ignore hydrogens in the RMSD calculation.
Returns
A list of lRMSDs with a value for each pair of rows in arl1 and arl2.
Definition at line 212 of file analyse.py.
         # Compare through every molecule pair.
         for i, (a1, a2) in enumerate(zip(arl1, arl2)):
             mol1 = a1.toatoms()
             mol2 = a2.toatoms()
             if len(mol1) != len(mol2):
                 raise ValueError(f'Atoms objects have different lengths! arl1 has length {len(arl1)}, while arl2 has length {len(arl2)}.')
             # Rotate/translate mol2 to get the least RMSD.
             minimize_rotation_and_translation(mol1, mol2)
             rmsd = 0.0
             for j, (atom1, atom2) in enumerate(zip(mol1, mol2)):
                 if atom1.symbol != atom2.symbol:
                     raise ValueError('Molecules have different atomic mapping!')
                 if ignore_H and atom1.symbol == 'H':
                     continue
                 pos_diff = np.linalg.norm(atom1.position - atom2.position)**2
                 rmsd += pos_diff
             rmsd *= 1/len(mol1)
             rmsd = np.sqrt(rmsd)
             rmsd_list[i] = rmsd
         return rmsd_list
     def plot_force_difference(self, reference, comparisons, plot_type='hist',
                               reference_name=None, comparison_names=None, title=None,
                               return_data=False, savefig=None):
         '''Plot the RMSDs of atomic forces between the molecules in DFdb sets compared
         to a reference set.
Referenced by DFdb.analyse.DFanalysis.plot_position_difference().
plot_force_difference()
def DFdb.analyse.DFanalysis.plot_force_difference (self, reference, comparisons, plot_type = 'hist', reference_name = None, comparison_names = None, title = None, return_data = False, savefig = None)
Plot the RMSDs of atomic forces between the molecules in DFdb sets compared to a reference set.
Either uses Seaborn to produce a rough histogram or histogram+KDE plot, or uses Scikit-learn to fit an accurate KDE plot and report mean and variance of the resulting data.
Return 0 is a Pandas DataFrame containing the accurate results from the KDE fit if the Scikit-learn implementation is used, else return 0 is None. Return 1 is a Pandas DataFrame of all the force RMSDs if return_data is true, else return 1 is None.
Parameters
reference List of AtomsRows with identical chemical formulae to those in comparison. comparisons List of comparative lists of AtomsRows with identical chemical formulae to those in reference. plot_type (Default: hist, Choices: [hist, hist+kde, kde]) The type of plot to produce. reference_name (Optional) Name of the reference dataset. comparison_names (Optional) List of names of the comparison datasets. title (Optional) Figure title for the graph. return_data (Default: False) Whether to include a DataFrame of all the lRMSD data used in plotting. savefig (Optional) Whether to save the figure to file. Leaving as None means no saving, otherwise a string containing the path to save to should be passed.
Definition at line 272 of file analyse.py.
         ]
         if plot_type not in plot_types:
             raise ValueError('Unrecognised plot_type! Must be one of [hist, hist+kde, kde].')
         num_plots = len(comparisons)
         if comparison_names:
             if not len(comparison_names)==num_plots:
                 raise ValueError('Number of strings in comparison_names doesn\'t match number of comparative lists.')
         # Check that savefig is valid, if present.
         if savefig:
             if type(savefig) is not str:
                 raise ValueError('Argument savefig should be None or a string.')
         # Calculate RMSDs for each comparative dataset.
         rmsds = [self._compare_forces(reference, comparison) for comparison in comparisons]
         # Gather struct_name data if needed.
         if return_data:
             mol_names = [row.struct_name for row in reference]
         output = [None, None]
         # Plot figure.
         if plot_type == 'kde':
             # Generate an accurate KDE plot with Scikit-learn and report mean/variance.
             fig, ax = plt.subplots(1, num_plots, sharey=True, constrained_layout=True, figsize=(10*num_plots, 10))
             sample_means = np.zeros(num_plots)
             means = np.zeros(num_plots)
             sample_variances = np.zeros(num_plots)
             variances = np.zeros(num_plots)
             sample_stdevs = np.zeros(num_plots)
             stdevs = np.zeros(num_plots)
             for i, rmsd_list in enumerate(rmsds):
                 x = np.linspace(min(rmsd_list), max(rmsd_list), 1000)
                 bandwidths = 10**np.linspace(-1, 1, 100)
                 grid = GridSearchCV(KernelDensity(kernel='gaussian'), {'bandwidth': bandwidths}, cv=LeaveOneOut().split(rmsd_list))
                 grid.fit(rmsd_list[:, None])
                 kde = KernelDensity(bandwidth=grid.best_params_['bandwidth'], kernel='gaussian')
                 kde.fit(rmsd_list[:, None])
                 logprob = kde.score_samples(x[:, None])
                 means[i] = np.mean(rmsd_list)
                 variances[i] = np.var(rmsd_list)
                 stdevs[i] = np.sqrt(variances[i])
                 sample_means[i] = np.mean(kde.sample(self.skl_kde_samples))
                 sample_variances[i] = np.var(kde.sample(self.skl_kde_samples))
                 sample_stdevs[i] = np.sqrt(sample_variances[i])
                 ax[i].fill_between(x, np.exp(logprob), alpha=0.5)
                 if i == 0:
                     ax[i].set_ylabel('Probability')
                 ax[i].set_xlabel(r'RMSD of atomic forces ($eV/\AA$/atom)')
                 if reference_name and comparison_names:
                     ax[i].set_title(f'{reference_name} vs {comparison_names[i]}')
             # Assemble DataFrame of statistical information for the KDE plot.
             stats_df = pd.DataFrame({
                 'Comparison': [f'{reference_name} vs {comparison_names[i]}' for i in range(num_plots)],
                 'Raw Data Mean': means,
                 'Sample Mean': sample_means,
                 'Raw Data Variance': variances,
                 'Sample Variance': sample_variances,
                 'Raw Data Stdev': stdevs,
                 'Sample Stdev': sample_stdevs
             })
             output[0] = stats_df
         else:
             # Generate a rough histogram/KDE plot with seaborn.
             fig, ax = plt.subplots(1, num_plots, sharey=True, constrained_layout=True, figsize=(10*num_plots, 10))
             for i, rmsd_list in enumerate(rmsds):
                 sns.histplot(rmsd_list, bins=15, kde=(True if plot_type=='hist+kde' else False), ax=ax[i])
                 ax[i].set_xlabel(r'RMSD of atomic forces ($eV/\AA$/atom)')
                 if reference_name and comparison_names:
                     ax[i].set_title(f'{reference_name} vs {comparison_names[i]}')
         if title:
             fig.suptitle(title)
         if savefig:
             fig.savefig(savefig, dpi=300)
         plt.show()
         # Assemble the full labelled lRMSD DataFrame is requested.
         if return_data:
             data1 = pd.DataFrame(mol_names, columns=['struct_name'])
             data2 = pd.DataFrame(np.array(rmsds).T, columns=[f'{reference_name} vs {comparison_names[i]}' for i in range(num_plots)])
             data3 = pd.concat([data1, data2], axis=1)
             output[1] = data3
         return output[0], output[1]
     def _compare_forces(self, arl1, arl2):
         '''Calculate the RMSDs of atomic forces between the molecules
         in two DFdb sets.
         The molecules in each of the sets should be calculated from the
         same structure files to ensure identical atomic mapping.
References DFdb.analyse.DFanalysis._compare_forces(), and DFdb.analyse.DFanalysis.skl_kde_samples.
_compare_forces()
def DFdb.analyse.DFanalysis._compare_forces (self, arl1, arl2) private
Calculate the RMSDs of atomic forces between the molecules in two DFdb sets.
The molecules in each of the sets should be calculated from the same structure files to ensure identical atomic mapping.
Parameters
arl1 List of AtomsRows containing a set of AtomsRows with identical chemical formulae to those in ari2. arl2 List of AtomsRows containing a set of AtomsRows with identical chemical formulae to those in ari1.
Definition at line 390 of file analyse.py.
             if len(mol1) != len(mol2):
                 raise ValueError('Atoms objects have different lengths!')
             forces1 = mol1.get_forces()
             forces2 = mol2.get_forces()
             rmsd = 0.0
             for f1, f2 in zip(forces1, forces2):
                 force_diff = np.linalg.norm(f1 - f2)**2
                 rmsd += force_diff
             rmsd *= 1/len(mol1)
             rmsd = np.sqrt(rmsd)
             rmsd_list[i] = rmsd
         return rmsd_list
     def plot_energy_difference(self, reference_set, comparison_sets,
                                plot_type='hist', reference_name=None,
                                comparison_names=None, title=None,
                                return_data=False, savefig=None):
         '''Plot the energy differences between identically structured molecules in
         DFdb sets compared to a reference set.
         Either uses Seaborn to produce a rough histogram or histogram+KDE plot, or
Referenced by DFdb.analyse.DFanalysis.plot_force_difference().
plot_energy_difference()
def DFdb.analyse.DFanalysis.plot_energy_difference (self, reference_set, comparison_sets, plot_type = 'hist', reference_name = None, comparison_names = None, title = None, return_data = False, savefig = None)
Plot the energy differences between identically structured molecules in DFdb sets compared to a reference set.
Either uses Seaborn to produce a rough histogram or histogram+KDE plot, or uses Scikit-learn to fit an accurate KDE plot and report mean and variance of the resulting data.
Each unique struct_name in a DFdb set must be accompanied by a corresponding energy reference, placed first in that set's list. For example, if there are 4 types of struct_name forming 4 sub-lists in 'reference_set', the first molecule of each sub-list should be a reference structure which all other energies will be compared against, eg. an optimised ground state structure.
Return 0 is a Pandas DataFrame containing the accurate results from the KDE fit if the Scikit-learn implementation is used, else return 0 is None. Return 1 is a Pandas DataFrame containing all of the energy differences if return_data is True, else return 1 is None.
Parameters
reference_set List of lists of AtomsRows, separated by struct_names. The first entry of each sub-list should be a reliable energy reference. comparison_sets List of comparative lists of AtomsRows, with sub-lists separated by struct_names. The first entry of each sub-list should be a reliable energy reference. plot_type (Default: hist, Choices: [hist, hist+kde, kde]) The type of plot to produce. reference_name (Optional) Name of the reference dataset. comparison_names (Optional) List of names of the comparison datasets. title (Optional) Figure title for the graph. return_data (Default: False) Whether to include a DataFrame of all the lRMSD data used in plotting. savefig (Optional) Whether to save the figure to file. Leaving as None means no saving, otherwise a string containing the path to save to should be passed.
Definition at line 446 of file analyse.py.
                 if struct_name != '':
                     if struct_name != structure.struct_name:
                         raise ValueError(f'struct_name mismatch in {struct_name} sub-list of reference_set.')
                 else:
                     struct_name = structure.struct_name
                 if i != 0:
                     all_mol_names.append(struct_name)
             if struct_name not in mol_names:
                 mol_names.append(struct_name)
             else:
                 raise ValueError('reference_set contains multiple lists with the same struct_name!')
         num_mol_types = len(mol_names)
         num_plots = len(comparison_sets)
         # Check that struct_names in all comparison_sets match those in reference_set.
         for s, comparison_set in enumerate(comparison_sets):
             temp_names = []
             for sublist in comparison_set:
                 struct_name = ''
                 for structure in sublist:
                     if struct_name != '':
                         if struct_name != structure.struct_name:
                             raise ValueError(f'struct_name mismatch in {struct_name} sub-list of comparison_set {s}.')
                     else:
                         struct_name = structure.struct_name
                 if struct_name not in temp_names:
                     temp_names.append(struct_name)
                 else:
                     raise ValueError('reference_set contains multiple lists with the same struct_name!')
             for i, name in enumerate(temp_names):
                 if name != mol_names[i]:
                     raise ValueError(f'struct_names in comparison_set {s} and reference_set do not match!')
         # Check that plot type is allowed.
         plot_types = [
             'hist',
             'hist+kde',
             'kde'
         ]
         if plot_type not in plot_types:
             raise ValueError('Unrecognised plot_type! Must be one of [hist, hist+kde, kde].')
         # Check that there is a name for each of the comparison sets.
         if comparison_names:
             if not len(comparison_names)==num_plots:
                 raise ValueError('Number of strings in comparison_names doesn\'t match number of comparative lists.')
         # Check that savefig is valid, if present.
         if savefig:
             if type(savefig) is not str:
                 raise ValueError('Argument savefig should be None or a string.')
         all_energy_diffs_by_set = []
         for s, comparison_set in enumerate(comparison_sets):
             energy_diffs_by_name = []
             for ref_sublist, comp_sublist in zip(reference_set, comparison_set):
                 energy_diffs = self._compare_energies(ref_sublist, comp_sublist)
                 energy_diffs_by_name.append(energy_diffs)
             all_energy_diffs = np.concatenate(energy_diffs_by_name).ravel()
             all_energy_diffs_by_set.append(all_energy_diffs)
         # (Finally) plot results.
         output = [None, None]
         if plot_type == 'kde':
             # Generate an accurate KDE plot with Scikit-learn and report mean/variance.
             fig, ax = plt.subplots(1, num_plots, sharey=True, constrained_layout=True, figsize=(10*num_plots, 10))
             sample_means = np.zeros(num_plots)
             means = np.zeros(num_plots)
             sample_variances = np.zeros(num_plots)
             variances = np.zeros(num_plots)
             sample_stdevs = np.zeros(num_plots)
             stdevs = np.zeros(num_plots)
             for i, all_energy_diffs in enumerate(all_energy_diffs_by_set):
                 x = np.linspace(min(all_energy_diffs), max(all_energy_diffs), 1000)
                 bandwidths = 10**np.linspace(-1, 1, 100)
                 grid = GridSearchCV(KernelDensity(kernel='gaussian'), {'bandwidth': bandwidths}, cv=LeaveOneOut().split(all_energy_diffs))
                 grid.fit(all_energy_diffs[:, None])
                 kde = KernelDensity(bandwidth=grid.best_params_['bandwidth'], kernel='gaussian')
                 kde.fit(all_energy_diffs[:, None])
                 logprob = kde.score_samples(x[:, None])
                 means[i] = np.mean(all_energy_diffs)
                 variances[i] = np.var(all_energy_diffs)
                 stdevs[i] = np.sqrt(variances[i])
                 sample_means[i] = np.mean(kde.sample(self.skl_kde_samples))
                 sample_variances[i] = np.var(kde.sample(self.skl_kde_samples))
                 sample_stdevs[i] = np.sqrt(sample_variances[i])
                 ax[i].fill_between(x, np.exp(logprob), alpha=0.5)
                 if i == 0:
                     ax[i].set_ylabel('Probability')
                 ax[i].set_xlabel('Relative energy difference (eV)')
                 if reference_name and comparison_names:
                     ax[i].set_title(f'{reference_name} vs {comparison_names[i]}')
             stats_df = pd.DataFrame({
                 'Comparison': [f'{reference_name} vs {comparison_names[i]}' for i in range(num_plots)],
                 'Raw Data Mean': means,
                 'Sample Mean': sample_means,
                 'Raw Data Variance': variances,
                 'Sample Variance': sample_variances,
                 'Raw Data Stdev': stdevs,
                 'Sample Stdev': sample_stdevs
             })
             output[0] = stats_df
         else:
             # Generate a rough histogram/KDE plot with seaborn.
             fig, ax = plt.subplots(1, num_plots, sharey=True, constrained_layout=True, figsize=(10*num_plots, 10))
             for i, all_energy_diffs in enumerate(all_energy_diffs_by_set):
                 sns.histplot(all_energy_diffs, bins=15, kde=(True if plot_type=='hist+kde' else False), ax=ax[i])
                 ax[i].set_xlabel('Relative energy difference (eV)')
                 if reference_name and comparison_names:
                     ax[i].set_title(f'{reference_name} vs {comparison_names[i]}')
         if title:
             fig.suptitle(title)
         if savefig:
             fig.savefig(savefig, dpi=300)
         plt.show()
         if return_data:
             data1 = pd.DataFrame(all_mol_names, columns=['struct_name'])
             data2 = pd.DataFrame(np.array(all_energy_diffs_by_set).T, columns=[f'{reference_name} vs {comparison_names[i]}' for i in range(num_plots)])
             data3 = pd.concat([data1, data2], axis=1)
             output[1] = data3
         return output[0], output[1]
     def _compare_energies(self, arl1, arl2):
         '''Compare relative energies of the molecules in two DFdb sets.
         Energies of each molecule in the sets get defined relative to a reference structure,
         eg. to the ground state structure, which will be read from the first AtomsRow. All
         molecules in each of the sets AND the reference should have the same chemical formulae.
         Parameters:
References DFdb.analyse.DFanalysis._compare_energies(), and DFdb.analyse.DFanalysis.skl_kde_samples.
_compare_energies()
def DFdb.analyse.DFanalysis._compare_energies (self, arl1, arl2) private
Compare relative energies of the molecules in two DFdb sets.
   Energies of each molecule in the sets get defined relative to a reference structure,
   eg. to the ground state structure, which will be read from the first AtomsRow. All
   molecules in each of the sets AND the reference should have the same chemical formulae.
Parameters
arl1 List of AtomsRows containing a set of AtomsRows with identical chemical formulae to those in ari2. arl2 List of AtomsRows containing a set of AtomsRows with identical chemical formulae to those in ari1.
Definition at line 611 of file analyse.py.
             rel_energy = (e1 - re1) - (e2 - re2)
             rel_energy_list[i] = rel_energy
         return rel_energy_list
 def ari2list(ari):
     '''Converts an AtomsRow Iterator object to a list of AtomsRow objects
     so they can be enumerated over.
     If a selection is made directly from the ASE Database object (using DFdatabase.dc.select),
     a lazy iterator over AtomsRows will be returned which gets destroyed after
     iterating over for the first time. This iterator also cannot be enumerated
     over.
     This can be fixed by preconverting the lazy iterator into a list. However,
     for large selections this can take up a large amount of memory.
Referenced by DFdb.analyse.DFanalysis.plot_energy_difference().
Member Data Documentation
skl_kde_samples
DFdb.analyse.DFanalysis.skl_kde_samples
int
Definition at line 41 of file analyse.py.
Referenced by DFdb.analyse.DFanalysis.plot_energy_difference(), DFdb.analyse.DFanalysis.plot_force_difference(), and DFdb.analyse.DFanalysis.plot_position_difference().
The documentation for this class was generated from the following file:
repo/DFdb/analyse.py